package com.docs.scanner.presentation.theme

import androidx.compose.ui.graphics.Color

// ─── Light ───
val md_primary            = Color(0xFF3D5A80)
val md_onPrimary          = Color(0xFFFFFFFF)
val md_primaryContainer   = Color(0xFFDCE6F2)
val md_onPrimaryContainer = Color(0xFF16263D)
val md_background         = Color(0xFFFCFCFB)
val md_onBackground       = Color(0xFF1B1B19)
val md_surface            = Color(0xFFFFFFFF)
val md_onSurface          = Color(0xFF1B1B19)
val md_surfaceVariant     = Color(0xFFF2F2EF)
val md_onSurfaceVariant   = Color(0xFF5C5C57)
val md_outline            = Color(0xFFC9C9C3)
val md_outlineVariant     = Color(0xFFE7E7E2)
val md_error              = Color(0xFFB3261E)
val md_onError            = Color(0xFFFFFFFF)
val md_errorContainer     = Color(0xFFF9DEDC)
val md_tertiary           = Color(0xFF4C7A57)

// ─── Dark ───
val md_primary_d            = Color(0xFFA9C0E4)
val md_onPrimary_d          = Color(0xFF14233A)
val md_primaryContainer_d   = Color(0xFF2A3F5C)
val md_onPrimaryContainer_d = Color(0xFFDCE6F2)
val md_background_d         = Color(0xFF121316)
val md_onBackground_d       = Color(0xFFE6E6E2)
val md_surface_d            = Color(0xFF1A1B1E)
val md_onSurface_d          = Color(0xFFE6E6E2)
val md_surfaceVariant_d     = Color(0xFF26272B)
val md_onSurfaceVariant_d   = Color(0xFFA6A6A0)
val md_outline_d            = Color(0xFF46474B)
val md_outlineVariant_d     = Color(0xFF2C2D31)
val md_error_d              = Color(0xFFF2B8B5)
val md_onError_d            = Color(0xFF601410)
val md_tertiary_d           = Color(0xFF8FBF9C)

// Семантические алиасы и цвета для компонентов Google Docs Style
val GoogleDocsPrimary = Color(0xFF3D5A80)
val GoogleDocsPrimaryLight = Color(0xFF90A4AE)
val GoogleDocsTextPrimary = Color(0xFF1B1B19)
val GoogleDocsTextSecondary = Color(0xFF5C5C57)
val GoogleDocsTextTertiary = Color(0xFF9AA0A6)
val GoogleDocsBackground = Color(0xFFFCFCFB)
val GoogleDocsSurface = Color(0xFFFFFFFF)
val GoogleDocsSurfaceVariant = Color(0xFFF2F2EF)
val GoogleDocsBorder = Color(0xFFE7E7E2)
val GoogleDocsBorderLight = Color(0xFFE7E7E2)
val GoogleDocsDivider = Color(0xFFE7E7E2)
val GoogleDocsError = Color(0xFFB3261E)
val GoogleDocsWarning = Color(0xFFFF9800)
val GoogleDocsSuccess = Color(0xFF4C7A57)
val GoogleDocsFabPrimary = Color(0xFF3D5A80)
val GoogleDocsFabSecondary = Color(0xFFFFFFFF)
val GoogleDocsFabShadow = Color(0x33000000)
val GoogleDocsButtonHover = Color(0xFFF2F2EF)
val GoogleDocsButtonText = Color(0xFF3D5A80)
val GoogleDocsTranslationBackground = Color(0xFFE8F5E9)
val GoogleDocsTranslationBorder = Color(0xFFC8E6C9)
val GoogleDocsTranslationIcon = Color(0xFF43A047)
val GoogleDocsTranslationText = Color(0xFF2E7D32)
val GoogleDocsTranslationTitle = Color(0xFF2E7D32)
val GoogleDocsAiLoadingDot = Color(0xFF3D5A80)
val GoogleDocsAiLoadingUnderline = Color(0xFF3D5A80)