package com.docs.scanner.data.local.database.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Fts4
import androidx.room.Index
import androidx.room.PrimaryKey

/*
 * ════════════════════════════════════════════════════════════════════════════════
 * ANALYTICS CENTER — ENTITIES
 * ════════════════════════════════════════════════════════════════════════════════
 *
 * Two independent surfaces inside the Analytics Hub:
 *
 *   1. Translation Archive (analytics_translations)
 *      A copy of every successful translation is mirrored here automatically
 *      from EditorViewModel. The archive is *autonomous*: editing or deleting
 *      an archive entry does NOT touch the source document and vice versa.
 *      We keep denormalized source metadata (record/folder names) so the
 *      archive is still meaningful after the source record was renamed or
 *      removed.
 *
 *   2. Notes (analytics_notes)
 *      User-authored notes — title + content + tags + colour. Fully detached
 *      from documents. Used as a free-form "Information Analysis" workspace.
 *
 * Both surfaces are exposed to global search via FTS4 mirror tables.
 *
 * Design choices:
 *  - NO foreign keys to documents/records. Source metadata is plain Long?/String?.
 *  - id is autogenerated Long, matching the rest of the project's PK style.
 *  - Timestamps default to 0L so Room migrations don't need NOW() workarounds;
 *    repositories always set them on insert/update.
 *  - `userModified` flag on translations lets the UI show "edited" badges and
 *    lets sync logic skip rewriting entries the user has touched.
 * ════════════════════════════════════════════════════════════════════════════════
 */

// ──────────────────────────────────────────────────────────────────────────────
// 1. TRANSLATION ARCHIVE
// ──────────────────────────────────────────────────────────────────────────────

/**
 * One row per translation event captured from the editor.
 *
 * Notes:
 *  - `translatedText` is the primary payload (always Russian per product spec,
 *    but the column stays generic so we can broaden languages later).
 *  - `originalText` is kept for context; nullable to allow user-created
 *    archive entries with no paired original.
 *  - `sourceLanguage`/`targetLanguage` use ISO codes (e.g. "en", "ru").
 */
@Entity(
    tableName = "analytics_translations",
    indices = [
        Index(value = ["created_at"]),
        Index(value = ["updated_at"]),
        Index(value = ["target_language"]),
        Index(value = ["source_record_id"])
    ]
)
data class AnalyticsTranslationEntity(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Long = 0,

    @ColumnInfo(name = "translated_text")
    val translatedText: String,

    @ColumnInfo(name = "original_text")
    val originalText: String? = null,

    @ColumnInfo(name = "source_language", defaultValue = "'auto'")
    val sourceLanguage: String = "auto",

    @ColumnInfo(name = "target_language", defaultValue = "'ru'")
    val targetLanguage: String = "ru",

    /**
     * Denormalized trace fields — set when the entry was mirrored from a
     * real document. Nullable because user can also create entries manually.
     */
    @ColumnInfo(name = "source_document_id")
    val sourceDocumentId: Long? = null,

    @ColumnInfo(name = "source_record_id")
    val sourceRecordId: Long? = null,

    @ColumnInfo(name = "source_record_name")
    val sourceRecordName: String? = null,

    @ColumnInfo(name = "source_folder_name")
    val sourceFolderName: String? = null,

    @ColumnInfo(name = "user_modified", defaultValue = "0")
    val userModified: Boolean = false,

    @ColumnInfo(name = "word_count", defaultValue = "0")
    val wordCount: Int = 0,

    @ColumnInfo(name = "created_at", defaultValue = "0")
    val createdAt: Long = 0L,

    @ColumnInfo(name = "updated_at", defaultValue = "0")
    val updatedAt: Long = 0L
)

/**
 * FTS4 mirror for global search.
 *
 * Uses `content=AnalyticsTranslationEntity` so the FTS table doesn't duplicate
 * storage — it just references the source table by rowid.
 *
 * Sync triggers are created in MIGRATION_20_21.
 */
@Entity(tableName = "analytics_translations_fts")
@Fts4(contentEntity = AnalyticsTranslationEntity::class)
data class AnalyticsTranslationFtsEntity(
    @ColumnInfo(name = "translated_text")
    val translatedText: String,

    @ColumnInfo(name = "original_text")
    val originalText: String?
)

// ──────────────────────────────────────────────────────────────────────────────
// 2. NOTES (Information Analysis)
// ──────────────────────────────────────────────────────────────────────────────

/**
 * Free-form note. Title + content + tags + colour swatch.
 *
 *  - `tags` is a JSON string array (re-using the same convention as records).
 *  - `color` is an optional ARGB hex string ("#FF8E24AA") consumed by the UI.
 *  - `isPinned` keeps a note at the top of the list.
 *  - `isArchived` hides a note from the default list but keeps it for restore.
 */
@Entity(
    tableName = "analytics_notes",
    indices = [
        Index(value = ["updated_at"]),
        Index(value = ["created_at"]),
        Index(value = ["is_pinned"]),
        Index(value = ["is_archived"])
    ]
)
data class AnalyticsNoteEntity(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Long = 0,

    @ColumnInfo(name = "title", defaultValue = "''")
    val title: String = "",

    @ColumnInfo(name = "content", defaultValue = "''")
    val content: String = "",

    /** JSON array of plain strings, e.g. `["analysis","draft"]`. Use TagsJson helpers. */
    @ColumnInfo(name = "tags", defaultValue = "'[]'")
    val tags: String = "[]",

    @ColumnInfo(name = "color")
    val color: String? = null,

    @ColumnInfo(name = "is_pinned", defaultValue = "0")
    val isPinned: Boolean = false,

    @ColumnInfo(name = "is_archived", defaultValue = "0")
    val isArchived: Boolean = false,

    @ColumnInfo(name = "created_at", defaultValue = "0")
    val createdAt: Long = 0L,

    @ColumnInfo(name = "updated_at", defaultValue = "0")
    val updatedAt: Long = 0L
)

/**
 * FTS4 mirror for global search across notes.
 */
@Entity(tableName = "analytics_notes_fts")
@Fts4(contentEntity = AnalyticsNoteEntity::class)
data class AnalyticsNoteFtsEntity(
    @ColumnInfo(name = "title")
    val title: String,

    @ColumnInfo(name = "content")
    val content: String
)